language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6
# command to install dependencies
install: 
    - pip install kafka-python
# command to run tests
script:
    python test.py
